# Generated by Django 5.2.1 on 2025-05-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_information_user_alter_information_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
